---
# tasks file for ansible-role-fgci-login

- name: setting Login as Internal network gateway on the install node
  lineinfile: backup=yes 
              dest=/etc/dhcp/dhcpd.conf 
              regexp="  option routers {{ kickstart_server_ip }};" 
              line="  option routers {{ int_gateway }};"
  when: chgIntGW is defined and chgIntGW == True
  register: reg_chgIntGW
  delegate_to: install

- name: restart dhcpd on the install node if we update the config
  service: name=dhcpd state=restarted
  delegate_to: install
  when: chgIntGW is defined and chgIntGW == True and reg_chgIntGW.changed
